
package com.client.userapp.views;

import com.client.userapp.Application;
import com.client.userapp.constants.WindowUtility;
import com.marksmana.info.Information;
import com.marksmana.info.SingleInformation;
import com.marksmana.utils.Json;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giang
 */
public class AboutFrame extends javax.swing.JPanel {

    /**
     * Creates new form AboutFrame
     */
    public AboutFrame() {
        initComponents();
        
        initTable();
        initAboutLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfoSchool = new javax.swing.JLabel();
        spr = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchoolInfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblAbout = new javax.swing.JLabel();

        lblInfoSchool.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInfoSchool.setText("Thông tin trường học");

        tblSchoolInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblSchoolInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Thông tin", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSchoolInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblSchoolInfo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblSchoolInfo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Thông tin phần mềm");

        lblAbout.setText("{ctx}");
        lblAbout.setToolTipText("");
        lblAbout.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblAbout.setMaximumSize(new java.awt.Dimension(35, 14));
        jScrollPane2.setViewportView(lblAbout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(spr)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(lblInfoSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoSchool)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spr, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblInfoSchool;
    private javax.swing.JSeparator spr;
    private javax.swing.JTable tblSchoolInfo;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        try {
            DefaultTableModel m = (DefaultTableModel) tblSchoolInfo.getModel();
            m.setRowCount(0);
            Information i = Json.DeserializeObject(
                    Application.PROP.get("school_info").toString().replace("\\\"", "\""), 
                    Information.class);
            for (SingleInformation si : i) {
                m.addRow(new String[] {si.getKey(), si.getValue()});
            }
        } catch (Exception ex) {
            WindowUtility.showMessage(this, "Lỗi", "Không lấy được thông tin trường học.", WindowUtility.ERROR);
        }
    }

    private void initAboutLabel() {
        StringBuilder ctx = new StringBuilder();
        ctx.append("<html><body><h4>Phần mềm quản lý điểm</h4>")
                .append("<quot>Phiên bản 1.0-U</quot><hr/><p style=\"width: 90%; padding: 0 5px;\">")
                .append("Phát triển bởi: <ul><li>Nguyễn Bằng Giang, </li><li>Phạm Xuân Đức,</li> <li>Lê Tiến Đạt,</li> <li>Ứng Đình Hướng,</li> <li>Nguyễn Phương Nam</li></ul>")
                .append("Biểu tượng và đồ họa: Nick Roach (GPL License); Paomedia (Creative Common)");
        ctx.append("</p></body></html>");
        lblAbout.setText(ctx.toString());
    }
}
