/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.userapp.views;

import com.client.service.Properties;
import com.client.userapp.Application;
import com.client.userapp.constants.WebMethods;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import static java.lang.System.exit;
import java.text.SimpleDateFormat;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Giang
 */
public class StartScreen extends javax.swing.JFrame {

    private Color bgr;

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
        setWindowProperties();
        lblStatus.setText("Xin chào!");
        
        loadIconImage();
        setIconImage(Application.ICON);

        setVisible(true);
        loadProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        pnlIcon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MyBudget");
        setBackground(new java.awt.Color(255, 204, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐIỂM");

        lblStatus.setText("WELCOME");

        pnlIcon.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //loadProcess();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlIcon;
    // End of variables declaration//GEN-END:variables

    private void loadProcess() {
        // Load data here
        try {
            lblStatus.setText("Đang bắt đầu...");
            initApplication();
        } catch (Exception ex) {
            lblStatus.setText("LỖI: Không có kết nối máy chủ");
            lblStatus.setForeground(Color.RED);
            JOptionPane.showMessageDialog(
                null, 
                "Không tìm thấy kết nối tới máy chủ dịch vụ khả dụng.\n\n"
                        + "Có thể bạn chưa có kết nối Internet, hãy kiểm tra và chạy lại.",
                "Lỗi kết nối Service", 
                JOptionPane.ERROR_MESSAGE);
            exit(100);
            return;
        }

        this.dispose();
    }
    
    private void initApplication() throws Exception{
        lblStatus.setText("Kết nối dịch vụ...");
        Application.PROP = new Hashtable<>();
        for (Properties p : WebMethods.getProperties()) {
            lblStatus.setText("Khởi tạo: "+p.getKey());
            Thread.sleep(110);
            Application.PROP.put(p.getKey(), p.getValue());
        }
        try {
            // TODO code application logic here
            lblStatus.setText("Tạo môi trường đồ họa...");
            Thread.sleep(300);
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            // ignore
        }
        try {
            Application.DATE_FORMAT = new SimpleDateFormat(Application.PROP.get("date_format").toString());
        } catch (Exception ex) {
            Application.DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
        }
        lblStatus.setText("Sẵn sàng");
        javax.swing.JFrame frm = new LoginScreen();
        frm.setVisible(true);
    }

    private void loadIconImage() {
        // new javax.swing.ImageIcon(getClass().getResource("/com/client/userapp/images/login.png"))
        try {
            lblStatus.setText("Nạp thành phần đồ họa...");
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/client/userapp/images/splash.png"));

            BufferedImage img;
            img = new BufferedImage(pnlIcon.getSize().height, pnlIcon.getSize().height, BufferedImage.TYPE_INT_ARGB);
            Graphics2D gr = img.createGraphics();
            gr.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            gr.drawImage(icon.getImage(), 0, 0, pnlIcon.getSize().height, pnlIcon.getSize().height, null);
            gr.dispose();

            JLabel lblImage = new JLabel(new ImageIcon(img));
            lblImage.setBackground(bgr);
            pnlIcon.setBackground(bgr);
            pnlIcon.add(lblImage);
            
            Application.ICON = new ImageIcon(getClass().getResource("/com/client/userapp/images/icon.png")).getImage();
        } catch (Exception ex) {
            // ignore
            System.out.println("Image load error");
        }
    }

    private void setWindowProperties() {
        bgr = new Color(144, 237, 214);
        setOpacity(0.86f);
        this.getContentPane().setBackground(bgr);
        setIconImage(Application.ICON); // Image icon = ImageIO.read(new File(Constants.file("ICON_SMALL")))
        setSize(Application.SCREEN_SIZE.width / 3, Application.SCREEN_SIZE.height / 3);
        setLocationRelativeTo(null);
        setResizable(false);
    }
}
